NAME=push_swap
CC=cc
FLAGS= -Wall -Wextra -Werror

all:$(NAME)

$(NAME):$(OBJ)
	ar rcs $(NAME) $(OBJ)

%.o:%.c
	$(CC) $(FLAGS) -c $< -o $@

clean:
	rm $(OBj)

fclean:clean
	rm -rf $(NAME)

re:fclean all

.PHONY:clean fclean re